{
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 52,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "RJNdb872coUu",
        "outputId": "cdf48fab-466e-45c0-c6e0-cb90b644179a"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n"
          ]
        }
      ],
      "source": [
        "from google.colab import drive\n",
        "drive.mount('/content/drive')"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "UfUhz7LpcvFS",
        "outputId": "5a7cdf3f-7f3b-4288-838b-bfc8d2c4ae28"
      },
      "outputs": [
        {
          "name": "stderr",
          "output_type": "stream",
          "text": [
            "ERROR: Could not find a version that satisfies the requirement tensorflow==2.4.0 (from versions: 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.10.0rc0)\n",
            "ERROR: No matching distribution found for tensorflow==2.4.0\n"
          ]
        },
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Collecting keras==2.4.3"
          ]
        },
        {
          "name": "stderr",
          "output_type": "stream",
          "text": [
            "  error: subprocess-exited-with-error\n",
            "  \n",
            "  × pip subprocess to install build dependencies did not run successfully.\n",
            "  │ exit code: 1\n",
            "  ╰─> [319 lines of output]\n",
            "      Ignoring numpy: markers 'python_version == \"3.5\" and platform_system != \"AIX\"' don't match your environment\n",
            "      Ignoring numpy: markers 'python_version == \"3.6\" and platform_system != \"AIX\"' don't match your environment\n",
            "      Ignoring numpy: markers 'python_version == \"3.7\" and platform_system != \"AIX\"' don't match your environment\n",
            "      Ignoring numpy: markers 'python_version == \"3.5\" and platform_system == \"AIX\"' don't match your environment\n",
            "      Ignoring numpy: markers 'python_version == \"3.6\" and platform_system == \"AIX\"' don't match your environment\n",
            "      Ignoring numpy: markers 'python_version == \"3.7\" and platform_system == \"AIX\"' don't match your environment\n",
            "      Ignoring numpy: markers 'python_version >= \"3.8\" and platform_system == \"AIX\"' don't match your environment\n",
            "      Collecting wheel\n",
            "        Downloading wheel-0.37.1-py2.py3-none-any.whl (35 kB)\n",
            "      Collecting setuptools\n",
            "        Downloading setuptools-63.4.1-py3-none-any.whl (1.2 MB)\n",
            "           ---------------------------------------- 1.2/1.2 MB 7.8 MB/s eta 0:00:00\n",
            "      Collecting Cython>=0.29.13\n",
            "        Downloading Cython-0.29.32-py2.py3-none-any.whl (986 kB)\n",
            "           ------------------------------------- 986.3/986.3 kB 20.8 MB/s eta 0:00:00\n",
            "      Collecting numpy==1.17.3\n",
            "        Downloading numpy-1.17.3.zip (6.4 MB)\n",
            "           ---------------------------------------- 6.4/6.4 MB 7.0 MB/s eta 0:00:00\n",
            "        Preparing metadata (setup.py): started\n",
            "        Preparing metadata (setup.py): finished with status 'done'\n",
            "      Collecting pybind11>=2.4.0\n",
            "        Downloading pybind11-2.10.0-py3-none-any.whl (213 kB)\n",
            "           -------------------------------------- 213.3/213.3 kB 3.3 MB/s eta 0:00:00\n",
            "      Using legacy 'setup.py install' for numpy, since package 'wheel' is not installed.\n",
            "      Installing collected packages: wheel, setuptools, pybind11, numpy, Cython\n",
            "        Running setup.py install for numpy: started\n",
            "        Running setup.py install for numpy: finished with status 'error'\n",
            "        error: subprocess-exited-with-error\n",
            "      \n",
            "        Ã— Running setup.py install for numpy did not run successfully.\n",
            "        â”‚ exit code: 1\n",
            "        â•°â”€> [277 lines of output]\n",
            "            Running from numpy source directory.\n",
            "      \n",
            "            Note: if you need reliable uninstall behavior, then install\n",
            "            with pip instead of using `setup.py install`:\n",
            "      \n",
            "              - `pip install .`       (from a git repo or downloaded source\n",
            "                                       release)\n",
            "              - `pip install numpy`   (last NumPy release on PyPi)\n",
            "      \n",
            "      \n",
            "            blas_opt_info:\n",
            "            blas_mkl_info:\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries mkl_rt not found in ['C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\libs']\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            blis_info:\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries blis not found in ['C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\libs']\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            openblas_info:\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries openblas not found in ['C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\libs']\n",
            "            get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'\n",
            "            customize GnuFCompiler\n",
            "            Could not locate executable g77\n",
            "            Could not locate executable f77\n",
            "            customize IntelVisualFCompiler\n",
            "            Could not locate executable ifort\n",
            "            Could not locate executable ifl\n",
            "            customize AbsoftFCompiler\n",
            "            Could not locate executable f90\n",
            "            customize CompaqVisualFCompiler\n",
            "            Could not locate executable DF\n",
            "            customize IntelItaniumVisualFCompiler\n",
            "            Could not locate executable efl\n",
            "            customize Gnu95FCompiler\n",
            "            Could not locate executable gfortran\n",
            "            Could not locate executable f95\n",
            "            customize G95FCompiler\n",
            "            Could not locate executable g95\n",
            "            customize IntelEM64VisualFCompiler\n",
            "            customize IntelEM64TFCompiler\n",
            "            Could not locate executable efort\n",
            "            Could not locate executable efc\n",
            "            customize PGroupFlangCompiler\n",
            "            Could not locate executable flang\n",
            "            don't know how to compile Fortran code on platform 'nt'\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            atlas_3_10_blas_threads_info:\n",
            "            Setting PTATLAS=ATLAS\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries tatlas not found in ['C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\libs']\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            atlas_3_10_blas_info:\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries satlas not found in ['C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\libs']\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            atlas_blas_threads_info:\n",
            "            Setting PTATLAS=ATLAS\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries ptf77blas,ptcblas,atlas not found in ['C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\libs']\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            atlas_blas_info:\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries f77blas,cblas,atlas not found in ['C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\libs']\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            accelerate_info:\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            C:\\Users\\prath\\AppData\\Local\\Temp\\pip-install-cbhov8w_\\numpy_2b3c8e78a7aa4a8a8e215fcecd6c63e0\\numpy\\distutils\\system_info.py:690: UserWarning:\n",
            "                Optimized (vendor) Blas libraries are not found.\n",
            "                Falls back to netlib Blas library which has worse performance.\n",
            "                A better performance should be easily gained by switching\n",
            "                Blas library.\n",
            "              self.calc_info()\n",
            "            blas_info:\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries blas not found in ['C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\libs']\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            C:\\Users\\prath\\AppData\\Local\\Temp\\pip-install-cbhov8w_\\numpy_2b3c8e78a7aa4a8a8e215fcecd6c63e0\\numpy\\distutils\\system_info.py:690: UserWarning:\n",
            "                Blas (http://www.netlib.org/blas/) libraries not found.\n",
            "                Directories to search for the libraries can be specified in the\n",
            "                numpy/distutils/site.cfg file (section [blas]) or by setting\n",
            "                the BLAS environment variable.\n",
            "              self.calc_info()\n",
            "            blas_src_info:\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            C:\\Users\\prath\\AppData\\Local\\Temp\\pip-install-cbhov8w_\\numpy_2b3c8e78a7aa4a8a8e215fcecd6c63e0\\numpy\\distutils\\system_info.py:690: UserWarning:\n",
            "                Blas (http://www.netlib.org/blas/) sources not found.\n",
            "                Directories to search for the sources can be specified in the\n",
            "                numpy/distutils/site.cfg file (section [blas_src]) or by setting\n",
            "                the BLAS_SRC environment variable.\n",
            "              self.calc_info()\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            'svnversion' is not recognized as an internal or external command,\n",
            "            operable program or batch file.\n",
            "            non-existing path in 'numpy\\\\distutils': 'site.cfg'\n",
            "            lapack_opt_info:\n",
            "            lapack_mkl_info:\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries mkl_rt not found in ['C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\libs']\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            openblas_lapack_info:\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries openblas not found in ['C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\libs']\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            openblas_clapack_info:\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries openblas,lapack not found in ['C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\libs']\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            flame_info:\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries flame not found in ['C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\libs']\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            atlas_3_10_threads_info:\n",
            "            Setting PTATLAS=ATLAS\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries lapack_atlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\lib\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries tatlas,tatlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\lib\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries lapack_atlas not found in C:\\\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries tatlas,tatlas not found in C:\\\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries lapack_atlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\libs\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries tatlas,tatlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\libs\n",
            "            <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            atlas_3_10_info:\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries lapack_atlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\lib\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries satlas,satlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\lib\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries lapack_atlas not found in C:\\\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries satlas,satlas not found in C:\\\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries lapack_atlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\libs\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries satlas,satlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\libs\n",
            "            <class 'numpy.distutils.system_info.atlas_3_10_info'>\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            atlas_threads_info:\n",
            "            Setting PTATLAS=ATLAS\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries lapack_atlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\lib\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries ptf77blas,ptcblas,atlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\lib\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries lapack_atlas not found in C:\\\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries ptf77blas,ptcblas,atlas not found in C:\\\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries lapack_atlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\libs\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries ptf77blas,ptcblas,atlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\libs\n",
            "            <class 'numpy.distutils.system_info.atlas_threads_info'>\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            atlas_info:\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries lapack_atlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\lib\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries f77blas,cblas,atlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\lib\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries lapack_atlas not found in C:\\\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries f77blas,cblas,atlas not found in C:\\\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries lapack_atlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\libs\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries f77blas,cblas,atlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\libs\n",
            "            <class 'numpy.distutils.system_info.atlas_info'>\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            lapack_info:\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries lapack not found in ['C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\libs']\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            C:\\Users\\prath\\AppData\\Local\\Temp\\pip-install-cbhov8w_\\numpy_2b3c8e78a7aa4a8a8e215fcecd6c63e0\\numpy\\distutils\\system_info.py:1712: UserWarning:\n",
            "                Lapack (http://www.netlib.org/lapack/) libraries not found.\n",
            "                Directories to search for the libraries can be specified in the\n",
            "                numpy/distutils/site.cfg file (section [lapack]) or by setting\n",
            "                the LAPACK environment variable.\n",
            "              if getattr(self, '_calc_info_{}'.format(lapack))():\n",
            "            lapack_src_info:\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            C:\\Users\\prath\\AppData\\Local\\Temp\\pip-install-cbhov8w_\\numpy_2b3c8e78a7aa4a8a8e215fcecd6c63e0\\numpy\\distutils\\system_info.py:1712: UserWarning:\n",
            "                Lapack (http://www.netlib.org/lapack/) sources not found.\n",
            "                Directories to search for the sources can be specified in the\n",
            "                numpy/distutils/site.cfg file (section [lapack_src]) or by setting\n",
            "                the LAPACK_SRC environment variable.\n",
            "              if getattr(self, '_calc_info_{}'.format(lapack))():\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\lib\\distutils\\dist.py:274: UserWarning: Unknown distribution option: 'define_macros'\n",
            "              warnings.warn(msg)\n",
            "            running install\n",
            "            running build\n",
            "            running config_cc\n",
            "            unifing config_cc, config, build_clib, build_ext, build commands --compiler options\n",
            "            running config_fc\n",
            "            unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options\n",
            "            running build_src\n",
            "            build_src\n",
            "            building py_modules sources\n",
            "            creating build\n",
            "            creating build\\src.win-amd64-3.9\n",
            "            creating build\\src.win-amd64-3.9\\numpy\n",
            "            creating build\\src.win-amd64-3.9\\numpy\\distutils\n",
            "            building library \"npymath\" sources\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            error: Microsoft Visual C++ 14.0 or greater is required. Get it with \"Microsoft C++ Build Tools\": https://visualstudio.microsoft.com/visual-cpp-build-tools/\n",
            "            [end of output]\n",
            "      \n",
            "        note: This error originates from a subprocess, and is likely not a problem with pip.\n",
            "      error: legacy-install-failure\n",
            "      \n",
            "      Ã— Encountered error while trying to install package.\n",
            "      â•°â”€> numpy\n",
            "      \n",
            "      note: This is an issue with the package mentioned above, not pip.\n",
            "      hint: See above for output from the failure.\n",
            "      [end of output]\n",
            "  \n",
            "  note: This error originates from a subprocess, and is likely not a problem with pip.\n",
            "error: subprocess-exited-with-error\n",
            "\n",
            "× pip subprocess to install build dependencies did not run successfully.\n",
            "│ exit code: 1\n",
            "╰─> See above for output.\n",
            "\n",
            "note: This error originates from a subprocess, and is likely not a problem with pip.\n"
          ]
        },
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "\n",
            "  Downloading Keras-2.4.3-py2.py3-none-any.whl (36 kB)\n",
            "Collecting numpy==1.19.3\n",
            "  Downloading numpy-1.19.3-cp39-cp39-win_amd64.whl (13.3 MB)\n",
            "     ---------------------------------------- 13.3/13.3 MB 5.0 MB/s eta 0:00:00\n",
            "Collecting pillow==7.0.0\n",
            "  Downloading Pillow-7.0.0.tar.gz (38.2 MB)\n",
            "     ---------------------------------------- 38.2/38.2 MB 5.0 MB/s eta 0:00:00\n",
            "  Preparing metadata (setup.py): started\n",
            "  Preparing metadata (setup.py): finished with status 'done'\n",
            "Collecting scipy==1.4.1\n",
            "  Downloading scipy-1.4.1.tar.gz (24.6 MB)\n",
            "     ---------------------------------------- 24.6/24.6 MB 5.2 MB/s eta 0:00:00\n",
            "  Installing build dependencies: started\n",
            "  Installing build dependencies: finished with status 'error'\n",
            "Collecting matplotlib==3.3.2\n",
            "  Downloading matplotlib-3.3.2.tar.gz (37.9 MB)\n",
            "     ---------------------------------------- 37.9/37.9 MB 5.5 MB/s eta 0:00:00\n",
            "  Preparing metadata (setup.py): started\n",
            "  Preparing metadata (setup.py): finished with status 'done'\n",
            "Collecting opencv-python\n",
            "  Downloading opencv_python-4.6.0.66-cp36-abi3-win_amd64.whl (35.6 MB)\n",
            "     ---------------------------------------- 35.6/35.6 MB 4.0 MB/s eta 0:00:00\n",
            "Collecting keras-resnet==0.2.0\n",
            "  Downloading keras-resnet-0.2.0.tar.gz (9.3 kB)\n",
            "  Preparing metadata (setup.py): started\n",
            "  Preparing metadata (setup.py): finished with status 'done'\n",
            "Requirement already satisfied: certifi>=2020.06.20 in c:\\users\\prath\\appdata\\local\\programs\\python\\python39\\lib\\site-packages (from matplotlib==3.3.2) (2022.6.15)\n",
            "Requirement already satisfied: cycler>=0.10 in c:\\users\\prath\\appdata\\local\\programs\\python\\python39\\lib\\site-packages (from matplotlib==3.3.2) (0.11.0)\n",
            "Requirement already satisfied: kiwisolver>=1.0.1 in c:\\users\\prath\\appdata\\local\\programs\\python\\python39\\lib\\site-packages (from matplotlib==3.3.2) (1.4.4)\n",
            "Requirement already satisfied: numpy>=1.15 in c:\\users\\prath\\appdata\\local\\programs\\python\\python39\\lib\\site-packages (from matplotlib==3.3.2) (1.23.1)\n",
            "Requirement already satisfied: pillow>=6.2.0 in c:\\users\\prath\\appdata\\local\\programs\\python\\python39\\lib\\site-packages (from matplotlib==3.3.2) (9.2.0)\n",
            "Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\\users\\prath\\appdata\\local\\programs\\python\\python39\\lib\\site-packages (from matplotlib==3.3.2) (3.0.9)\n",
            "Requirement already satisfied: python-dateutil>=2.1 in c:\\users\\prath\\appdata\\local\\programs\\python\\python39\\lib\\site-packages (from matplotlib==3.3.2) (2.8.2)\n",
            "Collecting keras>=2.2.4\n",
            "  Downloading keras-2.9.0-py2.py3-none-any.whl (1.6 MB)\n",
            "     ---------------------------------------- 1.6/1.6 MB 3.8 MB/s eta 0:00:00\n",
            "Requirement already satisfied: six>=1.5 in c:\\users\\prath\\appdata\\local\\programs\\python\\python39\\lib\\site-packages (from python-dateutil>=2.1->matplotlib==3.3.2) (1.16.0)\n",
            "Using legacy 'setup.py install' for matplotlib, since package 'wheel' is not installed.\n",
            "Using legacy 'setup.py install' for keras-resnet, since package 'wheel' is not installed.\n",
            "Installing collected packages: keras, opencv-python, keras-resnet, matplotlib\n",
            "  Running setup.py install for keras-resnet: started\n",
            "  Running setup.py install for keras-resnet: finished with status 'done'\n",
            "  Attempting uninstall: matplotlib\n",
            "    Found existing installation: matplotlib 3.5.2\n",
            "    Uninstalling matplotlib-3.5.2:\n"
          ]
        },
        {
          "name": "stderr",
          "output_type": "stream",
          "text": [
            "ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'c:\\\\users\\\\prath\\\\appdata\\\\local\\\\programs\\\\python\\\\python39\\\\lib\\\\site-packages\\\\matplotlib\\\\backends\\\\_backend_agg.cp39-win_amd64.pyd'\n",
            "Consider using the `--user` option or check the permissions.\n",
            "\n"
          ]
        },
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Collecting imageai\n",
            "  Downloading imageai-2.1.6-py3-none-any.whl (160 kB)\n",
            "     -------------------------------------- 160.9/160.9 kB 4.7 MB/s eta 0:00:00\n",
            "Collecting h5py==2.10.0\n",
            "  Downloading h5py-2.10.0.tar.gz (301 kB)\n",
            "     -------------------------------------- 301.1/301.1 kB 9.4 MB/s eta 0:00:00\n",
            "  Preparing metadata (setup.py): started\n",
            "  Preparing metadata (setup.py): finished with status 'done'\n",
            "Collecting pillow==7.0.0\n",
            "  Using cached Pillow-7.0.0.tar.gz (38.2 MB)\n",
            "  Preparing metadata (setup.py): started\n",
            "  Preparing metadata (setup.py): finished with status 'done'\n",
            "Requirement already satisfied: opencv-python in c:\\users\\prath\\appdata\\local\\programs\\python\\python39\\lib\\site-packages (from imageai) (4.6.0.66)\n",
            "Collecting keras==2.4.3\n",
            "  Using cached Keras-2.4.3-py2.py3-none-any.whl (36 kB)\n",
            "Collecting scipy==1.4.1\n",
            "  Using cached scipy-1.4.1.tar.gz (24.6 MB)\n",
            "  Installing build dependencies: started\n",
            "  Installing build dependencies: finished with status 'error'\n"
          ]
        },
        {
          "name": "stderr",
          "output_type": "stream",
          "text": [
            "WARNING: Ignoring invalid distribution -atplotlib (c:\\users\\prath\\appdata\\local\\programs\\python\\python39\\lib\\site-packages)\n",
            "WARNING: Ignoring invalid distribution -atplotlib (c:\\users\\prath\\appdata\\local\\programs\\python\\python39\\lib\\site-packages)\n",
            "  error: subprocess-exited-with-error\n",
            "  \n",
            "  × pip subprocess to install build dependencies did not run successfully.\n",
            "  │ exit code: 1\n",
            "  ╰─> [320 lines of output]\n",
            "      WARNING: Ignoring invalid distribution -atplotlib (c:\\users\\prath\\appdata\\local\\programs\\python\\python39\\lib\\site-packages)\n",
            "      Ignoring numpy: markers 'python_version == \"3.5\" and platform_system != \"AIX\"' don't match your environment\n",
            "      Ignoring numpy: markers 'python_version == \"3.6\" and platform_system != \"AIX\"' don't match your environment\n",
            "      Ignoring numpy: markers 'python_version == \"3.7\" and platform_system != \"AIX\"' don't match your environment\n",
            "      Ignoring numpy: markers 'python_version == \"3.5\" and platform_system == \"AIX\"' don't match your environment\n",
            "      Ignoring numpy: markers 'python_version == \"3.6\" and platform_system == \"AIX\"' don't match your environment\n",
            "      Ignoring numpy: markers 'python_version == \"3.7\" and platform_system == \"AIX\"' don't match your environment\n",
            "      Ignoring numpy: markers 'python_version >= \"3.8\" and platform_system == \"AIX\"' don't match your environment\n",
            "      Collecting wheel\n",
            "        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)\n",
            "      Collecting setuptools\n",
            "        Using cached setuptools-63.4.1-py3-none-any.whl (1.2 MB)\n",
            "      Collecting Cython>=0.29.13\n",
            "        Using cached Cython-0.29.32-py2.py3-none-any.whl (986 kB)\n",
            "      Collecting numpy==1.17.3\n",
            "        Using cached numpy-1.17.3.zip (6.4 MB)\n",
            "        Preparing metadata (setup.py): started\n",
            "        Preparing metadata (setup.py): finished with status 'done'\n",
            "      Collecting pybind11>=2.4.0\n",
            "        Using cached pybind11-2.10.0-py3-none-any.whl (213 kB)\n",
            "      Using legacy 'setup.py install' for numpy, since package 'wheel' is not installed.\n",
            "      WARNING: Ignoring invalid distribution -atplotlib (c:\\users\\prath\\appdata\\local\\programs\\python\\python39\\lib\\site-packages)\n",
            "      Installing collected packages: wheel, setuptools, pybind11, numpy, Cython\n",
            "        Running setup.py install for numpy: started\n",
            "        Running setup.py install for numpy: finished with status 'error'\n",
            "        error: subprocess-exited-with-error\n",
            "      \n",
            "        Ã— Running setup.py install for numpy did not run successfully.\n",
            "        â”‚ exit code: 1\n",
            "        â•°â”€> [277 lines of output]\n",
            "            Running from numpy source directory.\n",
            "      \n",
            "            Note: if you need reliable uninstall behavior, then install\n",
            "            with pip instead of using `setup.py install`:\n",
            "      \n",
            "              - `pip install .`       (from a git repo or downloaded source\n",
            "                                       release)\n",
            "              - `pip install numpy`   (last NumPy release on PyPi)\n",
            "      \n",
            "      \n",
            "            blas_opt_info:\n",
            "            blas_mkl_info:\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries mkl_rt not found in ['C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\libs']\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            blis_info:\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries blis not found in ['C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\libs']\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            openblas_info:\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries openblas not found in ['C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\libs']\n",
            "            get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'\n",
            "            customize GnuFCompiler\n",
            "            Could not locate executable g77\n",
            "            Could not locate executable f77\n",
            "            customize IntelVisualFCompiler\n",
            "            Could not locate executable ifort\n",
            "            Could not locate executable ifl\n",
            "            customize AbsoftFCompiler\n",
            "            Could not locate executable f90\n",
            "            customize CompaqVisualFCompiler\n",
            "            Could not locate executable DF\n",
            "            customize IntelItaniumVisualFCompiler\n",
            "            Could not locate executable efl\n",
            "            customize Gnu95FCompiler\n",
            "            Could not locate executable gfortran\n",
            "            Could not locate executable f95\n",
            "            customize G95FCompiler\n",
            "            Could not locate executable g95\n",
            "            customize IntelEM64VisualFCompiler\n",
            "            customize IntelEM64TFCompiler\n",
            "            Could not locate executable efort\n",
            "            Could not locate executable efc\n",
            "            customize PGroupFlangCompiler\n",
            "            Could not locate executable flang\n",
            "            don't know how to compile Fortran code on platform 'nt'\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            atlas_3_10_blas_threads_info:\n",
            "            Setting PTATLAS=ATLAS\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries tatlas not found in ['C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\libs']\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            atlas_3_10_blas_info:\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries satlas not found in ['C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\libs']\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            atlas_blas_threads_info:\n",
            "            Setting PTATLAS=ATLAS\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries ptf77blas,ptcblas,atlas not found in ['C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\libs']\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            atlas_blas_info:\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries f77blas,cblas,atlas not found in ['C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\libs']\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            accelerate_info:\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            C:\\Users\\prath\\AppData\\Local\\Temp\\pip-install-m105fjx1\\numpy_40b388d2fcba4e56a9c3dfdfc8cc1046\\numpy\\distutils\\system_info.py:690: UserWarning:\n",
            "                Optimized (vendor) Blas libraries are not found.\n",
            "                Falls back to netlib Blas library which has worse performance.\n",
            "                A better performance should be easily gained by switching\n",
            "                Blas library.\n",
            "              self.calc_info()\n",
            "            blas_info:\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries blas not found in ['C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\libs']\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            C:\\Users\\prath\\AppData\\Local\\Temp\\pip-install-m105fjx1\\numpy_40b388d2fcba4e56a9c3dfdfc8cc1046\\numpy\\distutils\\system_info.py:690: UserWarning:\n",
            "                Blas (http://www.netlib.org/blas/) libraries not found.\n",
            "                Directories to search for the libraries can be specified in the\n",
            "                numpy/distutils/site.cfg file (section [blas]) or by setting\n",
            "                the BLAS environment variable.\n",
            "              self.calc_info()\n",
            "            blas_src_info:\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            C:\\Users\\prath\\AppData\\Local\\Temp\\pip-install-m105fjx1\\numpy_40b388d2fcba4e56a9c3dfdfc8cc1046\\numpy\\distutils\\system_info.py:690: UserWarning:\n",
            "                Blas (http://www.netlib.org/blas/) sources not found.\n",
            "                Directories to search for the sources can be specified in the\n",
            "                numpy/distutils/site.cfg file (section [blas_src]) or by setting\n",
            "                the BLAS_SRC environment variable.\n",
            "              self.calc_info()\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            'svnversion' is not recognized as an internal or external command,\n",
            "            operable program or batch file.\n",
            "            non-existing path in 'numpy\\\\distutils': 'site.cfg'\n",
            "            lapack_opt_info:\n",
            "            lapack_mkl_info:\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries mkl_rt not found in ['C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\libs']\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            openblas_lapack_info:\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries openblas not found in ['C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\libs']\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            openblas_clapack_info:\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries openblas,lapack not found in ['C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\libs']\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            flame_info:\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries flame not found in ['C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\libs']\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            atlas_3_10_threads_info:\n",
            "            Setting PTATLAS=ATLAS\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries lapack_atlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\lib\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries tatlas,tatlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\lib\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries lapack_atlas not found in C:\\\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries tatlas,tatlas not found in C:\\\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries lapack_atlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\libs\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries tatlas,tatlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\libs\n",
            "            <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            atlas_3_10_info:\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries lapack_atlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\lib\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries satlas,satlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\lib\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries lapack_atlas not found in C:\\\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries satlas,satlas not found in C:\\\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries lapack_atlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\libs\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries satlas,satlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\libs\n",
            "            <class 'numpy.distutils.system_info.atlas_3_10_info'>\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            atlas_threads_info:\n",
            "            Setting PTATLAS=ATLAS\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries lapack_atlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\lib\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries ptf77blas,ptcblas,atlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\lib\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries lapack_atlas not found in C:\\\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries ptf77blas,ptcblas,atlas not found in C:\\\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries lapack_atlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\libs\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries ptf77blas,ptcblas,atlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\libs\n",
            "            <class 'numpy.distutils.system_info.atlas_threads_info'>\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            atlas_info:\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries lapack_atlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\lib\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries f77blas,cblas,atlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\lib\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries lapack_atlas not found in C:\\\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries f77blas,cblas,atlas not found in C:\\\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries lapack_atlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\libs\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries f77blas,cblas,atlas not found in C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\libs\n",
            "            <class 'numpy.distutils.system_info.atlas_info'>\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            lapack_info:\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            customize MSVCCompiler\n",
            "              libraries lapack not found in ['C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\prath\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\libs']\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            C:\\Users\\prath\\AppData\\Local\\Temp\\pip-install-m105fjx1\\numpy_40b388d2fcba4e56a9c3dfdfc8cc1046\\numpy\\distutils\\system_info.py:1712: UserWarning:\n",
            "                Lapack (http://www.netlib.org/lapack/) libraries not found.\n",
            "                Directories to search for the libraries can be specified in the\n",
            "                numpy/distutils/site.cfg file (section [lapack]) or by setting\n",
            "                the LAPACK environment variable.\n",
            "              if getattr(self, '_calc_info_{}'.format(lapack))():\n",
            "            lapack_src_info:\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            C:\\Users\\prath\\AppData\\Local\\Temp\\pip-install-m105fjx1\\numpy_40b388d2fcba4e56a9c3dfdfc8cc1046\\numpy\\distutils\\system_info.py:1712: UserWarning:\n",
            "                Lapack (http://www.netlib.org/lapack/) sources not found.\n",
            "                Directories to search for the sources can be specified in the\n",
            "                numpy/distutils/site.cfg file (section [lapack_src]) or by setting\n",
            "                the LAPACK_SRC environment variable.\n",
            "              if getattr(self, '_calc_info_{}'.format(lapack))():\n",
            "              NOT AVAILABLE\n",
            "      \n",
            "            C:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\lib\\distutils\\dist.py:274: UserWarning: Unknown distribution option: 'define_macros'\n",
            "              warnings.warn(msg)\n",
            "            running install\n",
            "            running build\n",
            "            running config_cc\n",
            "            unifing config_cc, config, build_clib, build_ext, build commands --compiler options\n",
            "            running config_fc\n",
            "            unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options\n",
            "            running build_src\n",
            "            build_src\n",
            "            building py_modules sources\n",
            "            creating build\n",
            "            creating build\\src.win-amd64-3.9\n",
            "            creating build\\src.win-amd64-3.9\\numpy\n",
            "            creating build\\src.win-amd64-3.9\\numpy\\distutils\n",
            "            building library \"npymath\" sources\n",
            "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
            "            error: Microsoft Visual C++ 14.0 or greater is required. Get it with \"Microsoft C++ Build Tools\": https://visualstudio.microsoft.com/visual-cpp-build-tools/\n",
            "            [end of output]\n",
            "      \n",
            "        note: This error originates from a subprocess, and is likely not a problem with pip.\n",
            "      error: legacy-install-failure\n",
            "      \n",
            "      Ã— Encountered error while trying to install package.\n",
            "      â•°â”€> numpy\n",
            "      \n",
            "      note: This is an issue with the package mentioned above, not pip.\n",
            "      hint: See above for output from the failure.\n",
            "      WARNING: Ignoring invalid distribution -atplotlib (c:\\users\\prath\\appdata\\local\\programs\\python\\python39\\lib\\site-packages)\n",
            "      WARNING: Ignoring invalid distribution -atplotlib (c:\\users\\prath\\appdata\\local\\programs\\python\\python39\\lib\\site-packages)\n",
            "      WARNING: Ignoring invalid distribution -atplotlib (c:\\users\\prath\\appdata\\local\\programs\\python\\python39\\lib\\site-packages)\n",
            "      [end of output]\n",
            "  \n",
            "  note: This error originates from a subprocess, and is likely not a problem with pip.\n",
            "error: subprocess-exited-with-error\n",
            "\n",
            "× pip subprocess to install build dependencies did not run successfully.\n",
            "│ exit code: 1\n",
            "╰─> See above for output.\n",
            "\n",
            "note: This error originates from a subprocess, and is likely not a problem with pip.\n",
            "WARNING: Ignoring invalid distribution -atplotlib (c:\\users\\prath\\appdata\\local\\programs\\python\\python39\\lib\\site-packages)\n",
            "WARNING: Ignoring invalid distribution -atplotlib (c:\\users\\prath\\appdata\\local\\programs\\python\\python39\\lib\\site-packages)\n",
            "WARNING: Ignoring invalid distribution -atplotlib (c:\\users\\prath\\appdata\\local\\programs\\python\\python39\\lib\\site-packages)\n"
          ]
        }
      ],
      "source": [
        "!pip install tensorflow==2.4.0\n",
        "!pip install keras==2.4.3 numpy==1.19.3 pillow==7.0.0 scipy==1.4.1 h5py==2.10.0 \n",
        "!pip install matplotlib==3.3.2 opencv-python keras-resnet==0.2.0\n",
        "!pip install imageai --upgrade"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 3,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "kwcPNC84lysr",
        "outputId": "a31a6a4f-a443-4299-b56f-45af6413abc8"
      },
      "outputs": [
        {
          "name": "stderr",
          "output_type": "stream",
          "text": [
            "'wget' is not recognized as an internal or external command,\n",
            "operable program or batch file.\n"
          ]
        }
      ],
      "source": [
        "!wget 'https://github.com/OlafenwaMoses/ImageAI/releases/download/1.0/yolo-tiny.h5'"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 4,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "ggVHRDQ3mjqG",
        "outputId": "e181bce2-8389-407f-ddac-7e5bd09cd315"
      },
      "outputs": [],
      "source": [
        "!mkdir Object_Recognition\n",
        "!mkdir Models\n",
        "!mkdir Input\n",
        "!mkdir Output\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 6,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "QIW1wdd9pSsl",
        "outputId": "908dc84c-1444-47b8-c7e1-a4b08b15ec00"
      },
      "outputs": [
        {
          "ename": "ModuleNotFoundError",
          "evalue": "No module named 'imageai'",
          "output_type": "error",
          "traceback": [
            "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
            "\u001b[1;32mc:\\PGDACC Section\\Sem 2\\Python\\Practicals\\recognizer.ipynb Cell 5\u001b[0m in \u001b[0;36m<cell line: 2>\u001b[1;34m()\u001b[0m\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/PGDACC%20Section/Sem%202/Python/Practicals/recognizer.ipynb#ch0000004?line=0'>1</a>\u001b[0m \u001b[39m# importing the required library  \u001b[39;00m\n\u001b[1;32m----> <a href='vscode-notebook-cell:/c%3A/PGDACC%20Section/Sem%202/Python/Practicals/recognizer.ipynb#ch0000004?line=1'>2</a>\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mimageai\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mDetection\u001b[39;00m \u001b[39mimport\u001b[39;00m ObjectDetection\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/PGDACC%20Section/Sem%202/Python/Practicals/recognizer.ipynb#ch0000004?line=2'>3</a>\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mimageai\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mDetection\u001b[39;00m \u001b[39mimport\u001b[39;00m ObjectDetection\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/PGDACC%20Section/Sem%202/Python/Practicals/recognizer.ipynb#ch0000004?line=3'>4</a>\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39mos\u001b[39;00m\n",
            "\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'imageai'"
          ]
        }
      ],
      "source": [
        "# importing the required library  \n",
        "from imageai.Detection import ObjectDetection\n",
        "from imageai.Detection import ObjectDetection\n",
        "import os\n",
        "from PIL import Image\n",
        "\n",
        "# instantiating the class  \n",
        "recognizer = ObjectDetection()  \n",
        "  \n",
        "# defining the paths  \n",
        "path_model = r\"/content/drive/MyDrive/yolo/Models/yolo-tiny.h5\"  \n",
        "path_input = r\"/content/drive/MyDrive/yolo/Input/pede1.jpg\"  \n",
        "path_output = r\"/content/drive/MyDrive/yolo/Output/newimage.jpg\"  \n",
        "  \n",
        "# using the setModelTypeAsTinyYOLOv3() function  \n",
        "recognizer.setModelTypeAsTinyYOLOv3()  \n",
        "# setting the path of the Model  \n",
        "recognizer.setModelPath(path_model)  \n",
        "# loading the model  \n",
        "recognizer.loadModel()  \n",
        "# calling the detectObjectsFromImage() function  \n",
        "recognition = recognizer.detectObjectsFromImage(  \n",
        "    input_image = path_input,  \n",
        "    output_image_path = path_output  \n",
        "    )  \n",
        "  \n",
        "# iterating through the items found in the image  \n",
        "for eachItem in recognition:  \n",
        "    print(eachItem[\"name\"] , \" : \", eachItem[\"percentage_probability\"])  \n",
        "\n",
        "im = Image.open(path_output)\n",
        " \n",
        "im.show()"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 7,
      "metadata": {
        "id": "DjfDpeX2wqNC"
      },
      "outputs": [
        {
          "ename": "FileNotFoundError",
          "evalue": "[Errno 2] No such file or directory: '/content/drive/MyDrive/yolo/Output/newimage.jpg'",
          "output_type": "error",
          "traceback": [
            "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[1;31mFileNotFoundError\u001b[0m                         Traceback (most recent call last)",
            "\u001b[1;32mc:\\PGDACC Section\\Sem 2\\Python\\Practicals\\recognizer.ipynb Cell 6\u001b[0m in \u001b[0;36m<cell line: 6>\u001b[1;34m()\u001b[0m\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/PGDACC%20Section/Sem%202/Python/Practicals/recognizer.ipynb#ch0000005?line=2'>3</a>\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mPIL\u001b[39;00m \u001b[39mimport\u001b[39;00m Image\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/PGDACC%20Section/Sem%202/Python/Practicals/recognizer.ipynb#ch0000005?line=4'>5</a>\u001b[0m \u001b[39m# creating a object\u001b[39;00m\n\u001b[1;32m----> <a href='vscode-notebook-cell:/c%3A/PGDACC%20Section/Sem%202/Python/Practicals/recognizer.ipynb#ch0000005?line=5'>6</a>\u001b[0m im \u001b[39m=\u001b[39m Image\u001b[39m.\u001b[39;49mopen(path_output)\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/PGDACC%20Section/Sem%202/Python/Practicals/recognizer.ipynb#ch0000005?line=7'>8</a>\u001b[0m im\u001b[39m.\u001b[39mshow()\n",
            "File \u001b[1;32mc:\\Users\\prath\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PIL\\Image.py:3092\u001b[0m, in \u001b[0;36mopen\u001b[1;34m(fp, mode, formats)\u001b[0m\n\u001b[0;32m   3089\u001b[0m     filename \u001b[39m=\u001b[39m fp\n\u001b[0;32m   3091\u001b[0m \u001b[39mif\u001b[39;00m filename:\n\u001b[1;32m-> 3092\u001b[0m     fp \u001b[39m=\u001b[39m builtins\u001b[39m.\u001b[39;49mopen(filename, \u001b[39m\"\u001b[39;49m\u001b[39mrb\u001b[39;49m\u001b[39m\"\u001b[39;49m)\n\u001b[0;32m   3093\u001b[0m     exclusive_fp \u001b[39m=\u001b[39m \u001b[39mTrue\u001b[39;00m\n\u001b[0;32m   3095\u001b[0m \u001b[39mtry\u001b[39;00m:\n",
            "\u001b[1;31mFileNotFoundError\u001b[0m: [Errno 2] No such file or directory: '/content/drive/MyDrive/yolo/Output/newimage.jpg'"
          ]
        }
      ],
      "source": [
        "path_output = r\"/content/drive/MyDrive/yolo/Output/newimage.jpg\" \n",
        "\n",
        "from PIL import Image\n",
        "\n",
        "# creating a object\n",
        "im = Image.open(path_output)\n",
        " \n",
        "im.show()\n"
      ]
    }
  ],
  "metadata": {
    "colab": {
      "collapsed_sections": [],
      "name": "recognizer.ipynb",
      "provenance": []
    },
    "kernelspec": {
      "display_name": "Python 3.9.13 64-bit",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.9.13"
    },
    "vscode": {
      "interpreter": {
        "hash": "93eedc92d5e8afb6a3d895e3e7c7a259ea6c50e115382a86e27456f2ca1a3d52"
      }
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}
